#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

	# ------------
	# Tests to run
	# ------------

	# -------------------------------
	# Default args to use for install
	# -------------------------------

	# -------------------------------
	# Commits to test upgrade from
	# -------------------------------
		test_upgrade_from.9de9cc90.name = "2023.09.17.22.15.57~ynh1 / packaging v1"
		test_upgrade_from.9de9cc90.args.domain = "domain.tld"
		test_upgrade_from.9de9cc90.args.path = "/path"
		test_upgrade_from.9de9cc90.args.is_public = 1
		test_upgrade_from.9de9cc90.args.admin = "john"
